// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceDataArray struct {
	DeviceDataItems      []*DeviceData `protobuf:"bytes,1,rep,name=DeviceDataItems,proto3" json:"DeviceDataItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceDataArray) Reset()         { *m = DeviceDataArray{} }
func (m *DeviceDataArray) String() string { return proto.CompactTextString(m) }
func (*DeviceDataArray) ProtoMessage()    {}
func (*DeviceDataArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *DeviceDataArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDataArray.Unmarshal(m, b)
}
func (m *DeviceDataArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDataArray.Marshal(b, m, deterministic)
}
func (m *DeviceDataArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDataArray.Merge(m, src)
}
func (m *DeviceDataArray) XXX_Size() int {
	return xxx_messageInfo_DeviceDataArray.Size(m)
}
func (m *DeviceDataArray) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDataArray.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDataArray proto.InternalMessageInfo

func (m *DeviceDataArray) GetDeviceDataItems() []*DeviceData {
	if m != nil {
		return m.DeviceDataItems
	}
	return nil
}

type DeviceData struct {
	DeviceId             *Guid          `protobuf:"bytes,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	DateTime             *DateTime      `protobuf:"bytes,2,opt,name=DateTime,proto3" json:"DateTime,omitempty"`
	DeviceValues         []*DeviceValue `protobuf:"bytes,3,rep,name=DeviceValues,proto3" json:"DeviceValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeviceData) Reset()         { *m = DeviceData{} }
func (m *DeviceData) String() string { return proto.CompactTextString(m) }
func (*DeviceData) ProtoMessage()    {}
func (*DeviceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *DeviceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceData.Unmarshal(m, b)
}
func (m *DeviceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceData.Marshal(b, m, deterministic)
}
func (m *DeviceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceData.Merge(m, src)
}
func (m *DeviceData) XXX_Size() int {
	return xxx_messageInfo_DeviceData.Size(m)
}
func (m *DeviceData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceData.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceData proto.InternalMessageInfo

func (m *DeviceData) GetDeviceId() *Guid {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *DeviceData) GetDateTime() *DateTime {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func (m *DeviceData) GetDeviceValues() []*DeviceValue {
	if m != nil {
		return m.DeviceValues
	}
	return nil
}

type DeviceValue struct {
	Obis                 [][]byte `protobuf:"bytes,1,rep,name=Obis,proto3" json:"Obis,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceValue) Reset()         { *m = DeviceValue{} }
func (m *DeviceValue) String() string { return proto.CompactTextString(m) }
func (*DeviceValue) ProtoMessage()    {}
func (*DeviceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *DeviceValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceValue.Unmarshal(m, b)
}
func (m *DeviceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceValue.Marshal(b, m, deterministic)
}
func (m *DeviceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceValue.Merge(m, src)
}
func (m *DeviceValue) XXX_Size() int {
	return xxx_messageInfo_DeviceValue.Size(m)
}
func (m *DeviceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceValue.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceValue proto.InternalMessageInfo

func (m *DeviceValue) GetObis() [][]byte {
	if m != nil {
		return m.Obis
	}
	return nil
}

func (m *DeviceValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Guid struct {
	Lo                   uint64   `protobuf:"fixed64,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi                   uint64   `protobuf:"fixed64,2,opt,name=hi,proto3" json:"hi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guid) Reset()         { *m = Guid{} }
func (m *Guid) String() string { return proto.CompactTextString(m) }
func (*Guid) ProtoMessage()    {}
func (*Guid) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *Guid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guid.Unmarshal(m, b)
}
func (m *Guid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guid.Marshal(b, m, deterministic)
}
func (m *Guid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guid.Merge(m, src)
}
func (m *Guid) XXX_Size() int {
	return xxx_messageInfo_Guid.Size(m)
}
func (m *Guid) XXX_DiscardUnknown() {
	xxx_messageInfo_Guid.DiscardUnknown(m)
}

var xxx_messageInfo_Guid proto.InternalMessageInfo

func (m *Guid) GetLo() uint64 {
	if m != nil {
		return m.Lo
	}
	return 0
}

func (m *Guid) GetHi() uint64 {
	if m != nil {
		return m.Hi
	}
	return 0
}

type DateTime struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTime) Reset()         { *m = DateTime{} }
func (m *DateTime) String() string { return proto.CompactTextString(m) }
func (*DateTime) ProtoMessage()    {}
func (*DateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *DateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTime.Unmarshal(m, b)
}
func (m *DateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTime.Marshal(b, m, deterministic)
}
func (m *DateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTime.Merge(m, src)
}
func (m *DateTime) XXX_Size() int {
	return xxx_messageInfo_DateTime.Size(m)
}
func (m *DateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTime.DiscardUnknown(m)
}

var xxx_messageInfo_DateTime proto.InternalMessageInfo

func (m *DateTime) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceDataArray)(nil), "main.DeviceDataArray")
	proto.RegisterType((*DeviceData)(nil), "main.DeviceData")
	proto.RegisterType((*DeviceValue)(nil), "main.DeviceValue")
	proto.RegisterType((*Guid)(nil), "main.Guid")
	proto.RegisterType((*DateTime)(nil), "main.DateTime")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0xd3, 0x18, 0xea, 0xa4, 0x54, 0x1d, 0x3c, 0xe4, 0x18, 0xf6, 0x50, 0x8a, 0x87, 0x1c,
	0x2a, 0x22, 0x78, 0x13, 0x02, 0xd2, 0x83, 0x08, 0x83, 0x78, 0x9f, 0x9a, 0x85, 0x2e, 0x24, 0xae,
	0xa4, 0xdb, 0x82, 0xbf, 0xc4, 0xbf, 0x2b, 0x3b, 0x5b, 0x9a, 0xd8, 0x5b, 0xde, 0xc7, 0xbc, 0xbc,
	0xb7, 0x00, 0x0d, 0x7b, 0xae, 0xbe, 0x7b, 0xe7, 0x1d, 0xa6, 0x1d, 0xdb, 0x2f, 0xfd, 0x0a, 0x57,
	0xb5, 0x39, 0xd8, 0x4f, 0x53, 0xb3, 0xe7, 0xe7, 0xbe, 0xe7, 0x1f, 0x7c, 0x1a, 0x53, 0x6b, 0x6f,
	0xba, 0x5d, 0xa1, 0xca, 0xc9, 0x32, 0x5f, 0x5d, 0x57, 0xe1, 0xa4, 0x1a, 0x44, 0x3a, 0x37, 0xea,
	0x5f, 0x05, 0x30, 0x70, 0xb8, 0x80, 0x69, 0x44, 0xeb, 0xa6, 0x50, 0xa5, 0x5a, 0xe6, 0x2b, 0x88,
	0x19, 0x2f, 0x7b, 0xdb, 0xd0, 0x49, 0xc3, 0x3b, 0x98, 0xd6, 0xec, 0xcd, 0xbb, 0xed, 0x4c, 0x91,
	0x88, 0x6f, 0x7e, 0xfc, 0xd7, 0x91, 0xa5, 0x93, 0x8e, 0x0f, 0x30, 0x8b, 0x77, 0x1f, 0xdc, 0xee,
	0xcd, 0xae, 0x98, 0x48, 0xb7, 0x9b, 0x71, 0x37, 0x51, 0xe8, 0x9f, 0x4d, 0x3f, 0x42, 0x3e, 0xc2,
	0x88, 0x90, 0xbe, 0x6d, 0x6c, 0x5c, 0x36, 0x23, 0xf9, 0xc6, 0x5b, 0xb8, 0x10, 0x51, 0x2a, 0x28,
	0x8a, 0x40, 0x2f, 0x20, 0x0d, 0x6d, 0x71, 0x0e, 0x49, 0xeb, 0x64, 0x45, 0x46, 0x49, 0xeb, 0x02,
	0xde, 0x5a, 0xb1, 0x66, 0x94, 0x6c, 0xad, 0x2e, 0x87, 0x0d, 0x21, 0xe9, 0x20, 0x49, 0xc1, 0x7e,
	0x49, 0x11, 0x6c, 0x32, 0x79, 0xf8, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xb5, 0x1d,
	0x64, 0x86, 0x01, 0x00, 0x00,
}
